services:
  web:
    image: prod-nginx-php-fpm8.2.3
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.3-fpm-bullseye'
    environment:
      PHP_VERSION: '8.3-fpm-bullseye'
#    volumes:
#     - ./app:/var/www/app
    networks:
      - taishin-net
    ports:
      - "80:80" #http
      - "443:443" #https
  web-db:
    container_name: web-db
    image: 'mysql:8.0'
    restart: always
    ports:
#      - '${FORWARD_DB_PORT:-3306}:3306'
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'taishinDB'
      MYSQL_USER: 'taishinUSR'
      MYSQL_PASSWORD: '!!t415h1n!!'
      MYSQL_ROOT_PASSWORD: '!!t415h1n!!'
    volumes:
      - 'taishin-mysql-volume:/var/lib/mysql'
      - ./app/docker/8.3-prod/my.cnf:/etc/mysql/my.cnf
    networks:
      - taishin-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 3
      timeout: 5s
networks:
  taishin-net:
    driver: bridge
volumes:
  taishin-mysql-volume:
    driver: local